export interface CurrencyListing {
  success: boolean;
  timestamp: number;
  base: string;
  date: string;
  rates: Rate;
}

export interface Rate {
  rates: {
    AED: string;
    AFN: string;
    ALL: string;
    AMD: string;
    ANG: string;
    AOA: string;
    ARS: string;
    AUD: string;
    AWG: string;
    AZN: string;
    BAM: string;
    BBD: string;
    BDT: string;
    BGN: string;
    BHD: string;
    BIF: string;
    BMD: string;
    BND: string;
    BOB: string;
    BRL: string;
    BSD: string;
    BTC: string;
    BTN: string;
    BWP: string;
    BYN: string;
    BYR: string;
    BZD: string;
    CAD: string;
    CDF: string;
    CHF: string;
    CLF: string;
    CLP: string;
    CNY: string;
    COP: string;
    CRC: string;
    CUC: string;
    CUP: string;
    CVE: string;
    CZK: string;
    DJF: string;
    DKK: string;
    DOP: string;
    DZD: string;
    EGP: string;
    ERN: string;
    ETB: string;
    EUR: string;
    FJD: string;
    FKP: string;
    GBP: string;
    GEL: string;
    GGP: string;
    GHS: string;
    GIP: string;
    GMD: string;
    GNF: string;
    GTQ: string;
    GYD: string;
    HKD: string;
    HNL: string;
    HRK: string;
    HTG: string;
    HUF: string;
    IDR: string;
    ILS: string;
    IMP: string;
    INR: string;
    IQD: string;
    IRR: string;
    ISK: string;
    JEP: string;
    JMD: string;
    JOD: string;
    JPY: string;
    KES: string;
    KGS: string;
    KHR: string;
    KMF: string;
    KPW: string;
    KRW: string;
    KWD: string;
    KYD: string;
    KZT: string;
    LAK: string;
    LBP: string;
    LKR: string;
    LRD: string;
    LSL: string;
    LTL: string;
    LVL: string;
    LYD: string;
    MAD: string;
    MDL: string;
    MGA: string;
    MKD: string;
    MMK: string;
    MNT: string;
    MOP: string;
    MRO: string;
    MUR: string;
    MVR: string;
    MWK: string;
    MXN: string;
    MYR: string;
    MZN: string;
    NAD: string;
    NGN: string;
    NIO: string;
    NOK: string;
    NPR: string;
    NZD: string;
    OMR: string;
    PAB: string;
    PEN: string;
    PGK: string;
    PHP: string;
    PKR: string;
    PLN: string;
    PYG: string;
    QAR: string;
    RON: string;
    RSD: string;
    RUB: string;
    RWF: string;
    SAR: string;
    SBD: string;
    SCR: string;
    SDG: string;
    SEK: string;
    SGD: string;
    SHP: string;
    SLL: string;
    SOS: string;
    SRD: string;
    STD: string;
    SVC: string;
    SYP: string;
    SZL: string;
    THB: string;
    TJS: string;
    TMT: string;
    TND: string;
    TOP: string;
    TRY: string;
    TTD: string;
    TWD: string;
    TZS: string;
    UAH: string;
    UGX: string;
    USD: string;
    UYU: string;
    UZS: string;
    VEF: string;
    VND: string;
    VUV: string;
    WST: string;
    XAF: string;
    XAG: string;
    XAU: string;
    XCD: string;
    XDR: string;
    XOF: string;
    XPF: string;
    YER: string;
    ZAR: string;
    ZMK: string;
    ZMW: string;
    ZWL: string;
  };
}

export const emptyCurrency = {
  success: false,
  timestamp: 0,
  base: '',
  date: '',
  rates: {
    AED: '',
    AFN: '',
    ALL: '',
    AMD: '',
    ANG: '',
    AOA: '',
    ARS: '',
    AUD: '',
    AWG: '',
    AZN: '',
    BAM: '',
    BBD: '',
    BDT: '',
    BGN: '',
    BHD: '',
    BIF: '',
    BMD: '',
    BND: '',
    BOB: '',
    BRL: '',
    BSD: '',
    BTC: '',
    BTN: '',
    BWP: '',
    BYN: '',
    BYR: '',
    BZD: '',
    CAD: '',
    CDF: '',
    CHF: '',
    CLF: '',
    CLP: '',
    CNY: '',
    COP: '',
    CRC: '',
    CUC: '',
    CUP: '',
    CVE: '',
    CZK: '',
    DJF: '',
    DKK: '',
    DOP: '',
    DZD: '',
    EGP: '',
    ERN: '',
    ETB: '',
    EUR: '',
    FJD: '',
    FKP: '',
    GBP: '',
    GEL: '',
    GGP: '',
    GHS: '',
    GIP: '',
    GMD: '',
    GNF: '',
    GTQ: '',
    GYD: '',
    HKD: '',
    HNL: '',
    HRK: '',
    HTG: '',
    HUF: '',
    IDR: '',
    ILS: '',
    IMP: '',
    INR: '',
    IQD: '',
    IRR: '',
    ISK: '',
    JEP: '',
    JMD: '',
    JOD: '',
    JPY: '',
    KES: '',
    KGS: '',
    KHR: '',
    KMF: '',
    KPW: '',
    KRW: '',
    KWD: '',
    KYD: '',
    KZT: '',
    LAK: '',
    LBP: '',
    LKR: '',
    LRD: '',
    LSL: '',
    LTL: '',
    LVL: '',
    LYD: '',
    MAD: '',
    MDL: '',
    MGA: '',
    MKD: '',
    MMK: '',
    MNT: '',
    MOP: '',
    MRO: '',
    MUR: '',
    MVR: '',
    MWK: '',
    MXN: '',
    MYR: '',
    MZN: '',
    NAD: '',
    NGN: '',
    NIO: '',
    NOK: '',
    NPR: '',
    NZD: '',
    OMR: '',
    PAB: '',
    PEN: '',
    PGK: '',
    PHP: '',
    PKR: '',
    PLN: '',
    PYG: '',
    QAR: '',
    RON: '',
    RSD: '',
    RUB: '',
    RWF: '',
    SAR: '',
    SBD: '',
    SCR: '',
    SDG: '',
    SEK: '',
    SGD: '',
    SHP: '',
    SLL: '',
    SOS: '',
    SRD: '',
    STD: '',
    SVC: '',
    SYP: '',
    SZL: '',
    THB: '',
    TJS: '',
    TMT: '',
    TND: '',
    TOP: '',
    TRY: '',
    TTD: '',
    TWD: '',
    TZS: '',
    UAH: '',
    UGX: '',
    USD: '',
    UYU: '',
    UZS: '',
    VEF: '',
    VND: '',
    VUV: '',
    WST: '',
    XAF: '',
    XAG: '',
    XAU: '',
    XCD: '',
    XDR: '',
    XOF: '',
    XPF: '',
    YER: '',
    ZAR: '',
    ZMK: '',
    ZMW: '',
    ZWL: '',
  },
};
